---
# USER GUIDE
  # All variables are mostly fixed, unless they have the comment '#changethis' trailing it

CompanyDataset: 
  rootpath: CompanyDataset
  sample: CompanyDataset/example.pcap_Flow.csv
  fullsize: csv/TEST_ISCX.csv #changethis

BaseDataset:
  "ddos2017": "CIC_IDS2017_Dataset/MachineLearningCVE/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv" #changethis
  "hoic": "/home/haktrak/Public/DDosHOIC.csv" #changethis
  "loic": "/home/haktrak/Public/DDosLOIC.csv" #changethis
  "cicids-whole": "/home/haktrak/Public/full_dataset.csv" #changethis
  "malicious-urls": "/home/haktrak/Public/ISCXURL2016/FinalDataset/original_malicious_urls.csv" #changethis
  "shuff1000train": "/home/haktrak/Public/full_datasets/shuffled_1000_train.csv"
  "shuff1000test": "/home/haktrak/Public/full_datasets/shuffled_1000_test.csv"

sample_pcap_path: TEST.pcap

# *Model/Pipeline Paths*
#   Set paths using the following convention
#   {DATASETNAME_MODELTYPE}: models/{model_name}
hoic_knnmodel: models/knnmodel.pkl
iscxurls_ridgeclassifier: models/countvectorizer-ridgeregression-pipeline.pkl
