---
CompanyDataset: 
  rootpath: CompanyDataset
  fullsize: CompanyDataset/haktrak.csv
  sample: CompanyDataset/example.pcap_Flow.csv

BaseDataset:
  "2017": "CIC_IDS2017_Dataset/MachineLearningCVE/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
  "2018": "/home/haktrak/Public/DDosHOIC.csv"
  "malicious-urls":
    "og": "/home/haktrak/Public/ISCXURL2016/FinalDataset/original_malicious_urls.csv"

pcap_name: "pcap/test.pcap"

# Model/Pipeline Paths
knnmodel_path: models/knnmodel.pkl
ridge-regression: models/countvectorizer-ridgeregression-pipeline.pkl

